name: Terraform CI with Checkov

on:
  push:
    branches:
      - main
      - lab2-datnguyen
  pull_request:
  workflow_dispatch:  # Enables manual trigger

permissions:
  id-token: write
  contents: read

jobs:
  terraform:
    name: Terraform Security and Deployment
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Debug OIDC Token
        run: |
          echo "Repository: ${{ github.repository }}"
          echo "Ref: ${{ github.ref }}"
          echo "Actor: ${{ github.actor }}"
          echo "Event: ${{ github.event_name }}"
          echo "SHA: ${{ github.sha }}"

      - name: Configure AWS credentials from OIDC
        uses: aws-actions/configure-aws-credentials@v3
        with:
          role-to-assume: arn:aws:iam::339712730141:role/gha_role2
          aws-region: us-east-1
          audience: sts.amazonaws.com

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.5.0

      - name: Terraform Init
        run: terraform init

      - name: Run Checkov for security scanning
        uses: bridgecrewio/checkov-action@master
        with:
          directory: .
          framework: terraform
          soft_fail: true
        continue-on-error: true

      - name: Terraform Plan
        run: terraform plan

      - name: Terraform Apply
        if: github.ref == 'refs/heads/main'
        run: terraform apply -auto-approve

      - name: Terraform Destroy (Manual Only)
        if: github.event_name == 'workflow_dispatch'
        run: terraform destroy -auto-approve
